import os
import asyncio
import logging
from typing import Dict, List, Tuple
import edge_tts
import config

# Set up logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

def save_tts_to_file(text: str, filename: str = "output_audio.wav") -> None:
    """Convert text to speech and save the output to a file using edge-tts.
    
    Args:
        text: The narration text to synthesize.
        filename: Destination path for the generated audio file.
    """
    async def _async_save() -> None:
        communicate = edge_tts.Communicate(
            text, 
            voice=config.DEFAULT_TTS_VOICE, 
            rate=config.DEFAULT_TTS_RATE
        )
        await communicate.save(filename)
    
    try:
        asyncio.run(_async_save())
        logger.info("Audio successfully saved to: %s", filename)
    except Exception as e:
        logger.error("Failed to generate TTS audio: %s", e)
        raise

def parse(narration_text: str, basedir: str) -> Tuple[List[Dict[str, str]], List[str]]:
    """Parse narration text containing image prompts and narrator text.
    
    Also writes the parsed subtitle content and details to files inside the directory.
    
    Args:
        narration_text: The complete raw script generated by Gemini.
        basedir: The base output directory for the short.
        
    Returns:
        A tuple of (parsed_data_list, list_of_raw_narrations).
    """
    data = []
    narrations = []
    lines = narration_text.split("\n")
    
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped or line_stripped.startswith('#'):
            continue
        elif line_stripped.startswith('Narrator: '):
            text = line_stripped.replace('Narrator: ', '').strip('"')
            data.append({
                "type": "text",
                "content": text,
            })
            narrations.append(text)
        elif line_stripped.startswith('['):
            background = line_stripped.strip('[]')
            data.append({
                "type": "image",
                "description": background,
            })
            
    # Write the title (first narration text line)
    text_elements = [el["content"] for el in data if el["type"] == "text"]
    if text_elements:
        title_path = os.path.join(basedir, "title.txt")
        with open(title_path, 'w', encoding='utf-8') as file:
            file.write(text_elements[0])
            
    # Write descriptions (narrations) to a text file
    desc_path = os.path.join(basedir, "description.txt")
    with open(desc_path, 'w', encoding='utf-8') as file:
        file.write("\n".join(narrations))
        
    logger.info("Successfully parsed script with %d scenes.", len(narrations))
    return data, narrations

def create(data: List[Dict[str, str]], output_folder: str) -> None:
    """Create individual narration audio files from parsed script data.
    
    Args:
        data: List of parsed narration dicts.
        output_folder: Directory to save generated narration files.
    """
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    n = 0
    for element in data:
        if element["type"] != "text":
            continue

        n += 1
        output_file = os.path.join(output_folder, f"narration_{n}.mp3")
        save_tts_to_file(text=element["content"], filename=output_file)
        logger.info("Saved narration %d to %s", n, output_file)
